version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./laravel:/var/www
      - /var/www/vendor
      - /var/www/node_modules
    networks:
      - laravel
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    env_file:
      - .env
    ports:
      - "8080:80"
    volumes:
      - ./laravel:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

  node:
    image: node:20
    container_name: node_build
    working_dir: /var/www
    ports:
      - "5173:5173"
    volumes:
      - ./laravel:/var/www
    command: sh -c "npm install && npm run dev -- --host" 
    networks:
      - laravel

networks:
  laravel:

volumes:
  db_data:


